image: composer:latest

before_script:
  - apk --no-cache add pcre-dev ${PHPIZE_DEPS} && pecl install xdebug && docker-php-ext-enable xdebug && apk del pcre-dev ${PHPIZE_DEPS}
  - git clone https://gitlab.com/baptistehardy/musikwald.git && cd musikwald
  - composer install

coverage:
  stage: test
  only:
    - master
  script:
    - php bin/phpunit --coverage-text --colors=never

tests:
  stage: test
  only:
    - master
  script:
    - php bin/phpunit --testdox
